insert into personajes values
(1, 'Rick Prime',
'Rick Sanchez de la Dimensión Prime, también conocido como Rick Prime, es el antagonista principal de la serie animada para adultos de ciencia ficción de Adult Swim, Rick y Morty.',
'Es el responsable de la muerte de la esposa del Rick protagonista  , quien lo considera su mayor nemesis y que gasto toda su vida buscandólo.',
'https://preview.redd.it/what-do-you-think-the-overall-goals-of-rick-prime-are-v0-s31835wyajyb1.jpg?auto=webp&s=e7eb01d3072693d8c31c108cad115d24cbfb841a',
'https://static.wikia.nocookie.net/rick-y-morty-espanol/images/0/09/RickPrime3.jpg/revision/latest/scale-to-width-down/1000?cb=20230225203714&path-prefix=es',
'https://static.wikia.nocookie.net/rick-y-morty-espanol/images/7/72/Rick_prime2.webp/revision/latest?cb=20230225203533&path-prefix=es',
'https://static.wikia.nocookie.net/rick-y-morty-espanol/images/2/2c/RIckPrimeYC137.png/revision/latest/scale-to-width-down/1000?cb=20230317201041&path-prefix=es'),
(2, 'Rick Sánchez',
'Richard Daniel "Rick" Sánchez de la Dimensión C-137 es un viejo científico alcohólico que acostumbra hablar de manera vulgar y entre eructos aparte de hablar de forma bastante inapropiada constantemente, la mayoría de las veces tiene un rastro de saliva e incluso se cree que es licor en la boca. Es padre de Beth Smith y el abuelo materno de Summer y Morty.',
'Es un hombre que ha pasado gran parte de su vida viajando a través de diversas dimensiones dando a entender que Morty es muy poco inteligente al punto de ser casi un retrasado.',
'https://pyxis.nymag.com/v1/imgs/bb2/701/c4787eccc4a76307518ae0632fb9196faa-rick-and-morty.rsquare.w400.jpg',
'https://static.wikia.nocookie.net/rick-y-morty-espanol/images/0/09/RickPrime3.jpg/revision/latest/scale-to-width-down/1000?cb=20230225203714&path-prefix=es',
'https://static.wikia.nocookie.net/rick-y-morty-espanol/images/7/72/Rick_prime2.webp/revision/latest?cb=20230225203533&path-prefix=es',
'https://static.wikia.nocookie.net/rick-y-morty-espanol/images/2/2c/RIckPrimeYC137.png/revision/latest/scale-to-width-down/1000?cb=20230317201041&path-prefix=es'),
(3, 'Summer Smith',
'Summer Smith de la Dimension C-131 es una de los cinco personajes principales. Es miembro de la familia Smith e hija de Jerry Smith y Beth Smith, la hermana mayor de Morty Smith y la madre de Naruto Smith.',
'Tiene tez blanca con cabeza ovalada, pelo castaño claro y su oreja saliendo justo a la mitad de la cabeza con 2 ojos redondos y grandes con una pupila pequeña. Utiliza una camisa verde con unas franjas marrones en la mitad con un pantalón marrón claro.',
'https://wallpapers.com/images/featured/summer-smith-klnzh3lxnmrcsz4u.jpg',
'https://wallpapers.com/images/featured/summer-smith-klnzh3lxnmrcsz4u.jpg',
'https://wallpapers.com/images/featured/summer-smith-klnzh3lxnmrcsz4u.jpg',
'https://wallpapers.com/images/featured/summer-smith-klnzh3lxnmrcsz4u.jpg'),
(4, 'Jerry Smith',
'Jerry Smith de la Dimension 5152 es uno de los protagonistas principales de la serie animada para Adulltos Rick y Morty es el yerno de 35 años de Rick Sánchez, esposo de Beth Smith y padre de Summer Smith y Morty Smith. Rick lo odia, no sabe cortejar a su mujer y ante sus hijos, es incapaz de admitir que está equivocado. A pesar de eso, hace lo que puede para ayudar ante los problemas cotidianos y sobrenaturales. Cuando más adelante en la serie se queda sin trabajo comienza a entrenar abejas, su familia no deja de reprochárselo, haciéndole sentir inseguro ante sus propios hijos.',
'Tiene tez blanca con cabeza ovalada, pelo castaño claro y su oreja saliendo justo a la mitad de la cabeza con 2 ojos redondos y grandes con una pupila pequeña. Utiliza una camisa verde con unas franjas marrones en la mitad con un pantalón marrón claro.',
'https://cdn.superaficionados.com/imagenes/jerry-smith.jpg',
'https://cdn.superaficionados.com/imagenes/jerry-smith.jpg',
'https://cdn.superaficionados.com/imagenes/jerry-smith.jpg',
'https://cdn.superaficionados.com/imagenes/jerry-smith.jpg'),
(5, 'Beth Smith',
'Beth Smith (nombre de soltera Beth Sánchez) de la Dimension C-131 es una de las protagonistas de la serie animada para adultos Rick y Morty Es la hija de Rick es la hija de un Rick muerto en un accidente, a lo que el Rick y Morty protagonistas ocuparon sus lugares. Es la esposa de Jerry y la madre de Summer y de Morty (quién murió en el mismo accidente que Rick).',
'Su vida ocurrida antes del Píloto de la serie es poco conocida, se sabe que fue abandonada de pequeña por su padre por razones desconocidas. Anhelaba ser cirujana cardíaca pero a los 17 años de edad fue a una fiesta con Jerry y quedó embarazada de Summer, pero aún así logro ir a la universidad y graduarse como cirujana de caballos, aunque ella ha admitido que contemplaba la posibilidad de abortar a Summer.',
'https://miro.medium.com/v2/resize:fit:640/0*iZ6etqJRQ9DPQtb6.jpg',
'https://miro.medium.com/v2/resize:fit:640/0*iZ6etqJRQ9DPQtb6.jpg',
'https://miro.medium.com/v2/resize:fit:640/0*iZ6etqJRQ9DPQtb6.jpg',
'https://miro.medium.com/v2/resize:fit:640/0*iZ6etqJRQ9DPQtb6.jpg'),
(6, 'Morty Smith',
'Morty Smith es uno de los personajes principales de la serie animada Rick y Morty, del canal de televisión Adult Swim. Creado por Justin Roiland y Dan Harmon, Morty es un nervioso adolescente basado en Marty McFly de Regreso al Futuro.1​ Conocido por su inquietud, torpeza y su cuestionable y dudosa personalidad, el personaje ha sido bien recibido por los seguidores de la serie. Es un joven, afable e impresionable chico que puede ser manipulado fácilmente.',
'Es formalmente llamado como Morty Smith C-137 por el Consejo Transdimensional de Ricks, en referencia a su universo original, C-137. Roiland fue el encargado de poner el nombre a ambos personajes, Rick y Morty.2​',
'https://a1cf74336522e87f135f-2f21ace9a6cf0052456644b80fa06d4f.ssl.cf2.rackcdn.com/images/characters/large/800/Morty-Smith.Rick-and-Morty.webp',
'https://a1cf74336522e87f135f-2f21ace9a6cf0052456644b80fa06d4f.ssl.cf2.rackcdn.com/images/characters/large/800/Morty-Smith.Rick-and-Morty.webp',
'https://a1cf74336522e87f135f-2f21ace9a6cf0052456644b80fa06d4f.ssl.cf2.rackcdn.com/images/characters/large/800/Morty-Smith.Rick-and-Morty.webp',
'https://a1cf74336522e87f135f-2f21ace9a6cf0052456644b80fa06d4f.ssl.cf2.rackcdn.com/images/characters/large/800/Morty-Smith.Rick-and-Morty.webp'),
(7, 'Tammy Guterman',
'Tamantha Tammy Guterman es una de las principales antagonistas de la serie de ciencia ficción animada para adultos Rick y Morty.',
'Tammy era una agente encubierta de la Federación Galáctica y la supuesta hija de Pat Gueterman y Donna Gueterman. También fue estudiante en la Escuela Secundaria Harry Herpson y amiga cercana de Summer Smith. Estaba comprometida con Persona Fénix y planeó una boda como una estratagema para reunir a tantos enemigos de la Federación Galáctica en un solo lugar para capturarlos y arrestarlos. Después de la caída de la Federación, se convirtió en la líder de los restos. Sin embargo, Rick la mató después cuando intentaba cazar a Beth Espacial.',
'https://i.ytimg.com/vi/7SwUgND2XvU/maxresdefault.jpg',
'https://i.ytimg.com/vi/7SwUgND2XvU/maxresdefault.jpg',
'https://i.ytimg.com/vi/7SwUgND2XvU/maxresdefault.jpg',
'https://i.ytimg.com/vi/7SwUgND2XvU/maxresdefault.jpg'),
(8, 'Morty Malvado',
'Evil Morty (en español, conocido como Morty Malvado) es uno de los antagonistas de la serie, Por razones desconocidas él ganó un gran odio hacia los Ricks, matando a distintas versiones de ellos, mientras capturaba a otras versiones de sí mismo para utilizar sus ondas cerebrales como escudo para ocultar su guarida del Consejo. es una de las muchas variantes de Morty en la Curva Finita Central.',
'Después de que Rick fuera asesinado por una horda de Mortys rabiosos él es "rescatado" por el Consejo de Ricks y se supone que fue de regreso a su dimensión de origen, después de hacer una autopsia a su Rick se dan cuenta de que alguien más lo estaba controlando de manera inalámbrica a lo que se ve posteriormente que en su parche hay unos cables los cuales funcionan de transmisor.',
'https://boxtv.com.mx/wp-content/uploads/2020/09/Morty-malvado-teoria.png',
'https://boxtv.com.mx/wp-content/uploads/2020/09/Morty-malvado-teoria.png',
'https://boxtv.com.mx/wp-content/uploads/2020/09/Morty-malvado-teoria.png',
'https://boxtv.com.mx/wp-content/uploads/2020/09/Morty-malvado-teoria.png'),
(9, 'Diane Sánchez',
'Diane Sanchez es la esposa fallecida de Rick Sánchez y la madre de Beth Sanchez La muerte de Diane fue el momento decisivo en la vida de Rick que lo convirtió en quien es. La historia de Diane ha sido el misterio general de la serie desde la primera temporada hasta la quinta temporada. Fue asesinada por Rick Prime a través de la explosión de una bomba futurista. El trauma de su asesinato hizo que Rick se convirtiera en una persona vengativa y transtornada, enviándolo a un viaje para tomar venganza por la muerte de su esposa encontrando al Rick que la mató.',
'Diane era la esposa de Rick Sanchez y la madre de Beth. No se ha revelado mucho sobre cómo era realmente su relación con Rick debido a declaraciones contradictorias en el transcurso de la serie. Sin embargo, se puede suponer que tuvieron un matrimonio feliz, como se muestra en el flashback (ligeramente modificado) en The Rickshank Rickdemption. El Sr. Nimbus parece haber conocido a Rick el tiempo suficiente para al menos saber quién era Diane, aunque no está claro si realmente la conocía (como se muestra en "Mort Dinner Rick Andre").',
'https://static1.srcdn.com/wordpress/wp-content/uploads/2020/09/Diane-Sanchez-Rick-and-Morty.jpg',
'https://static1.srcdn.com/wordpress/wp-content/uploads/2020/09/Diane-Sanchez-Rick-and-Morty.jpg',
'https://static1.srcdn.com/wordpress/wp-content/uploads/2020/09/Diane-Sanchez-Rick-and-Morty.jpg',
'https://static1.srcdn.com/wordpress/wp-content/uploads/2020/09/Diane-Sanchez-Rick-and-Morty.jpg'),
(10, 'Meeseeks',
'Mr Meeseeks es el nombre de todos los Meeseeks convocados activando una Caja del Sr. Meeseeks. Los Meeseeks aparecen en el quinto episodio de la primera temporada, "Meeseeks Destructores". Se sabe que habitan planetas en todo el universo.',
'Los Meeseeks son criaturas que se crean para servir a un propósito singular para el que se esforzarán por cumplir. Después de que cumplen su propósito, expiran y desaparecen en el aire. Su motivación para ayudar a los demás proviene del hecho de que la existencia es dolorosa para un Meeseeks, y la única forma de ser eliminado de la existencia es completar la tarea que fueron llamados a realizar. La violencia física no puede eliminarlos.',
'https://miro.medium.com/v2/resize:fit:643/1*0pCpQ0EUIkAwjolstINb6w.png',
'https://miro.medium.com/v2/resize:fit:643/1*0pCpQ0EUIkAwjolstINb6w.png',
'https://miro.medium.com/v2/resize:fit:643/1*0pCpQ0EUIkAwjolstINb6w.png',
'https://miro.medium.com/v2/resize:fit:643/1*0pCpQ0EUIkAwjolstINb6w.png');